---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  - name: Validate configuration
    ansible.builtin.command: "vector validate"
    register: vector_validate
    failed_when: vector_validate.rc != 0 or vector_validate.rc != 78

  # - name: Example assertion
  #   ansible.builtin.assert:
  #     that: vector_validate.rc == 0 or vector_validate.rc == 78
