---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  - name: Validate configuration
    ansible.builtin.command: "vector validate --no-environment"
    register: vector_validate

  # - name: debug
  #   ansible.builtin.debug:
  #     var: vector_validate

  - name: Example assertion
    ansible.builtin.assert:
      that: vector_validate.rc == 0
