---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: aragast
    image: docker.io/aragast/netology:latest
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
